### ISSUE TITLE
Bind $PWD option

### ISSUE THREAD

**Issue by JonahDW** [IanHeywood/oxkat#24] opened 2020-09-01 10:18 UTC
Trying to run oxkat on a dataset on a mounted directory, however it seems singularity binds to my home folder and can't see the mount from there, so none of the scripts can be found. I see that in `config.py` the option `BIND = '$PWD'` is present, but it doesn't seem to be used anywhere.

I think activating this option would solve my problem, I can try to make it work for the moment by just putting it into `submit_1GC_jobs.sh`, but a solution that would involve me doing less work every time would be preferable :).

If I massively overlooked something or am completely wrong, I'd be happy to hear it.

**Comment by IanHeywood** [comment] 2020-09-01 10:36
Hi @JonahDW. You are the opposite of completely wrong. Sorry for the hassle, finishing this is on the to-do list. I've also been replacing the `exec` in the submit script with `exec --bind $PWD` and cursing myself.

The issue is that the singularity exec call is made inside the setup scripts. I'd like to move that into the job_handler function (and add virtualenv functionality while I'm at it) to make things neater.

Thanks for nudging me.

**Comment by JonahDW** [comment] 2020-09-02 13:37
I might have spoken a bit too soon regarding this solving my problem. It seems that though singularity can see my measurement set that I've symlink'd, it can't see into the MS? So when it tries to open the table SPECTRAL_WINDOW in one of the first steps, it fails. Pretty sure this has to do with the symlink, but I'm trying to avoid copying enormous amounts of data everytime.

**Comment by IanHeywood** [comment] 2020-09-02 13:44
If the problem is what I think it is then I think a workaround is to set an environment variable, e.g.:

```
$ export MSDIR=/path/to/my/ms/folder
```

then you can set:

```
--bind $PWD,$MSDIR
```

when invoking singularity...

**Comment by JonahDW** [comment] 2020-09-03 09:14
That seems to do the trick. 

Worthy of note might be that 
`export SINGULARITY_BINDPATH="$PWD,$MSDIR"`
Works in the bash script (in the case of 'node' at least), and saves some time rewriting it for every singularity call

**Comment by IanHeywood** [comment] 2020-09-07 15:42
Thanks @JonahDW this is an excellent point and I think it can lead to an easy way to enable the binds via the config file and just have an export call in the bash scripts generated by the setup files.

However in testing this out I just ran into this puzzling difference between what bash stores in the `$PWD` environment variable, and what Python's `os.getcwd()` returns:

```
In [1]: import os

In [2]: os.getcwd()
Out[2]: '/ndidi/ianh/TKAT/recent/1598130064'

In [3]: !echo $PWD
/mnt/ndidi/ianh/TKAT/recent/1598130064
```

As such the full paths to the scripts in the bash files are missing the `/mnt` prefix and everything crashes...

**Comment by IanHeywood** [comment] 2020-09-07 15:45
`abspath` also ain't:

```
In [6]: os.path.abspath('.')
Out[6]: '/ndidi/ianh/TKAT/recent/1598130064'
```

**Comment by o-smirnov** [comment] 2020-09-07 17:19
OK hang on @IanHeywood, the Python in your previous two comments, this is *inside* the container?

**Comment by IanHeywood** [comment] 2020-09-08 08:35
Nope, outside the container, but that's where I am when running the setup script that needs these two things to give the same answer.

**Comment by o-smirnov** [comment] 2020-09-08 08:40
And is ``/mnt/ndidi`` the same as ``/ndidi``? Which one is the real one?

**Comment by IanHeywood** [comment] 2020-09-08 08:45
If you log into the machine then either will work. I think /ndidi just points to /mnt/ndidi.

But I pass $PWD (/mnt/ndidi/ianh/) to the $SINGULARITY_BINDPATH. The container starts up and runs a bash script generated by Python that points to files at /ndidi/ianh, and fails to find them.

I suppose I can have Python code write the `export SINGULARITY_BINDPATH ...` call so the contents of `os.getcwd()` gets passed to it.

**Comment by o-smirnov** [comment] 2020-09-08 08:50
Why not reset ``PWD`` to something consistent? I think ``os.environ['PWD'] = os.getcwd()`` should  work.

Also, try looking at ``os.path.realpath('.')``, that ought to eliminate all symlinks (unlike abspath).

**Comment by IanHeywood** [comment] 2020-09-08 11:09
> `os.environ['PWD'] = os.getcwd()`

This does work, but reverts when I exit Python, so will be different again by the time the generated script is run.

I think I'll just try to have Python write explicit paths everywhere and avoid the use of `$PWD` entirely. It's bound to fail somehow if someone comes along running a Timbuktunix distro but I'll worry about that later.

**Comment by IanHeywood** [comment] 2020-09-08 11:55
OK I think I can summarise the problem as follows:

1) I absolutely have to have the full /mnt/ndidi path with the mnt prefix for singularity to be happy.

2) I can't get Python to pick up anything other than the /ndidi path.

**Comment by o-smirnov** [comment] 2020-09-08 12:17
Did you try ``os.path.realpath()``?

**Comment by IanHeywood** [comment] 2020-09-08 12:23
Yeah same issue, doesn't pick up the /mnt prefix:

```
ianh@ndidi:~$ cd /mnt/ndidi/ianh/
ianh@ndidi:/mnt/ndidi/ianh$ ipython
Python 3.6.9 (default, Jul 17 2020, 12:50:27)
Type "copyright", "credits" or "license" for more information.

IPython 5.5.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import os

In [2]: os.path.realpath('.')
Out[2]: '/ndidi/ianh'
```

The solution seems to be to bind both`$PWD` and whatever `os.path.getcwd()` returns, but I'll take ugly and working over elegant and broken all day long.

@JonahDW if you want to try the "binding" branch it will hopefully have the necessary fixes. You should be able to set the `BIND` variable in `config.py` to a comma-separated list of whatever paths you need.

**Comment by JonahDW** [comment] 2020-09-08 12:49
> @JonahDW if you want to try the "binding" branch it will hopefully have the necessary fixes. You should be able to set the `BIND` variable in `config.py` to a comma-separated list of whatever paths you need.

Thanks @IanHeywood , that works well, maximal laziness can now be achieved.

**Comment by IanHeywood** [comment] 2020-09-08 13:07
> maximal laziness can now be achieved

It's what I strive for.

**Comment by IanHeywood** [comment] 2020-09-08 16:19
Hopefully fixed via this https://github.com/IanHeywood/oxkat/pull/25

**Closed by IanHeywood** 2020-09-08 16:19 UTC
