### ISSUE TITLE
DDfacet and killMS settings issue...

### ISSUE THREAD

**Issue by mauriliopannella** [IanHeywood/oxkat#48] opened 2022-03-17 09:48 UTC
Hi Ian,
I am trying a DD self-calibration run on my ms. As you suggest I bribed my sm to increase the max shared memory to 75% (not enough  I guess) and when the run starts I still get some warning messages: 

 - 12:44:31 - DDFacet            |   Max shared memory size is 75% of total RAM size; 75% currently available
 - 12:44:31 - DDFacet            | WARNING: sysctl vm.max_map_count = 65530. 
            This may be too little for large DDFacet and killMS jobs. If you get strange "file exists" 
            errors on /dev/shm, them try to bribe, beg or threaten your friendly local sysadmin into 
            setting vm.max_map_count=1000000 in /etc/sysctl.conf.
 - 12:44:31 - DDFacet            | WARNING: your system has a limit on memory locks configured.
            This may possibly slow down DDFacet performance. You can try removing the limit by running
                $ ulimit -l unlimited
            If this gives an "operation not permitted" error, you can try to bribe, beg or threaten 
            your friendly local sysadmin into doing
                # echo "*        -   memlock     unlimited" >> /etc/security/limits.conf

So the run goes for about seven hours and then it crushes looking for a file that does not exist on disk:

==============================================================

 - 19:06:38 - ClassFacetMachineT [0.4/1.1 1.5/2.4 1.9Gb] Taking facet directions from solutions file: killMS.killms-cohjones.sols.npz
 - 19:06:39 - DDFacet            [0.4/1.1 1.5/2.4 1.9Gb] Traceback (most recent call last):
  File "/usr/local/bin/DDF.py", line 455, in <module>
    main(OP, messages)
  File "/usr/local/bin/DDF.py", line 282, in main
    Imager.Init()
  File "/usr/local/lib/python3.6/dist-packages/DDFacet/Imager/ClassDeconvMachine.py", line 289, in Init
    self.CreateFacetMachines()
  File "/usr/local/lib/python3.6/dist-packages/DDFacet/Imager/ClassDeconvMachine.py", line 327, in CreateFacetMachines
    self.FacetMachine.appendMainField(ImageName="%s.image"%self.BaseName,**MainFacetOptions)
  File "/usr/local/lib/python3.6/dist-packages/DDFacet/Imager/ClassFacetMachine.py", line 283, in appendMainField
    self.setFacetsLocs()
  File "/usr/local/lib/python3.6/dist-packages/DDFacet/Imager/ClassFacetMachineTessel.py", line 123, in setFacetsLocs
    ClusterNodes = np.load(SolsFile)["ClusterCat"]
  File "/usr/local/lib/python3.6/dist-packages/numpy/lib/npyio.py", line 416, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'killMS.killms-cohjones.sols.npz'
 - 19:06:39 - DDFacet            [0.4/1.1 1.5/2.4 1.9Gb] There was a problem after 0m8.6s; if you think this is a bug please open an issue
...
Using python package located at: /usr/local/lib/python3.6/dist-packages/DDFacet
Using driver file located at: /usr/local/bin/DDF.py
....
Exception ignored in: <bound method ClassFacetMachine.__del__ of <DDFacet.Imager.ClassFacetMachineTessel.ClassFacetMachineTessel object at 0x7fdf92ad6940>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/DDFacet/Imager/ClassFacetMachine.py", line 176, in __del__
  File "/usr/local/lib/python3.6/dist-packages/DDFacet/Imager/ClassFacetMachine.py", line 186, in releaseGrids
AttributeError: 'ClassFacetMachineTessel' object has no attribute 'DicoGridMachine'

===================================================================

Any suggestion or clue you might have would be greatly appreciated!

Thanks,
Maurilio

**Comment by IanHeywood** [comment] 2022-03-17 10:53
Hi Maurilio. That is the second DDFacet run where it is expecting killMS solutions to be available, which is what the missing file should contain. It looks like this fails immediately:

```
There was a problem after 0m8.6s
```

So perhaps the either preceding killMS run failed, or even the DDFacet run prior to that which is used to setup the sky model for killMS to work with. Do the logs for the two previous steps give any clues? The killMS logging might be a bit lacking, but there should be good logs for the first DDFacet run in the IMAGES folder.

**Comment by mauriliopannella** [comment] 2022-03-17 11:23
OK, that would make sense :( So, before the bribing, I had started this run that eventually crushed at a relatively early time. After that, and without doing any cleaning or files check, I just restarted the 3GC_facet run... my bad. I guess I'll start over and see what happens. Thank you (again)!

**Comment by mauriliopannella** [comment] 2022-03-20 07:26
Hi Ian,
so I let it go for the full run again and it seems I got the issue with killMS. It seems it cannot find the kMS.py:
/.singularity.d/actions/exec: 21: exec: kMS.py: not found
Could it be the container was corrupted, didn't dowload properly or? 

Maurilio

**Comment by IanHeywood** [comment] 2022-03-20 17:20
Hi Maurilio, which killMS container is being used?

**Comment by mauriliopannella** [comment] 2022-03-20 17:37
in my containers dir I have this sif file killms_2.7.0.sif but then I see that the call to kMS.py looks like this:

# Run killMS
singularity exec /beegfs/clustersxcosmo/oxkat/containers/ddfacet_0.6.0.sif kMS.py .... 

is that OK?

**Comment by IanHeywood** [comment] 2022-03-20 18:06
I think I see the problem. I have a container that contains both DDF and kMS, but the ones that get pulled by the shell script are two separate ones. The default config reflects the former but not the latter.

If you change this line:

https://github.com/IanHeywood/oxkat/blob/master/oxkat/config.py#L54

so the killMS container looks for 'killms' then hopefully it should pick up the correct one for your setup...

Sorry for the lost time!

**Comment by mauriliopannella** [comment] 2022-03-21 09:57
Hi Ian,

the killms now starts running indeed but still crushes with the error below:

-----
    main(OP=OP,MSName=MSName)
  File "/usr/local/bin/kMS.py", line 500, in main
    GD=GDPredict)
  File "/usr/local/lib/python2.7/dist-packages/DDFacet/Data/ClassVisServer.py", line 91, in __init__
    self.Init()
  File "/usr/local/lib/python2.7/dist-packages/DDFacet/Data/ClassVisServer.py", line 179, in Init
    self.GD["RIME"]["PolMode"])
  File "/usr/local/lib/python2.7/dist-packages/DDFacet/Data/ClassStokes.py", line 161, in __init__
    raise ValueError("Image polarization descriptor must be stokes string or string list")
ValueError: Image polarization descriptor must be stokes string or string list
----

A couple of weird things I noticed:

1) it seems killms is using python 2.7 instead of 3.x. If that is OK, could it be a syntax issue?
2) when running ddfacet, athough still complaining about the max shared memory, it recognizes the value that the local sm has set (75%). Instead killms seems not to recognize it and it goes back to 'standard' set-up value (max shared memory size is only 50% of total RAM size...). Does that make any sense?

Thanks again for your help and commitment, I truly appreciate your effort here!

**Comment by IanHeywood** [comment] 2022-03-21 12:52
OK I'm sure that's an incompatibility between a Python 3 version of DDFacet and an older Python 2.7 version of killMS.
Can you please try replacing the killMS container with this one?

```
$ singularity pull docker://bhugo/killms:301
```

Hopefully that will contain a Python 3 version.

**Comment by mauriliopannella** [comment] 2022-03-22 07:57
Not much luck with the python3 version either... it still crushes with a similar input format error as before.
---
Traceback (most recent call last):
  File "/usr/local/bin/kMS.py", line 1321, in <module>
    main(OP=OP,MSName=MSName)
  File "/usr/local/bin/kMS.py", line 598, in main
    PreparePredict=ClassImageSM.ClassPreparePredict(BaseImageName,VS_DDFacet,IdSharedMem,GD=GDPredict)#,IdSharedMem=IdSharedMem)
  File "/usr/local/lib/python3.6/dist-packages/killMS/Predict/ClassImageSM2.py", line 104, in __init__
    self.CreateFacetMachines()
  File "/usr/local/lib/python3.6/dist-packages/DDFacet/Imager/ClassDeconvMachine.py", line 327, in CreateFacetMachines
    self.FacetMachine.appendMainField(ImageName="%s.image"%self.BaseName,**MainFacetOptions)
  File "/usr/local/lib/python3.6/dist-packages/DDFacet/Imager/ClassFacetMachine.py", line 283, in appendMainField
    self.setFacetsLocs()
  File "/usr/local/lib/python3.6/dist-packages/DDFacet/Imager/ClassFacetMachineTessel.py", line 591, in setFacetsLocs
    for i in range(len(LPolygonNew))]
  File "/usr/local/lib/python3.6/dist-packages/DDFacet/Imager/ClassFacetMachineTessel.py", line 591, in <listcomp>
    for i in range(len(LPolygonNew))]
TypeError: %i format: a number is required, not numpy.ndarray
---

**Comment by IanHeywood** [comment] 2022-03-22 10:46
I'm not sure about this... Was a suitable region file passed to killMS?

If so I can see if I can replicate the problem using the same pair of containers.

**Comment by bennahugo** [comment] 2022-03-22 11:01
As discussed offline with Ian
The following looks like a possible culprit:
https://github.com/saopicc/DDFacet/blob/master/DDFacet/Imager/ClassFacetMachineTessel.py#L383
I think it is running into a case where two solutions are precisely equidistant from the facet centre where the solutions must be applied (ie this is returning an array)?

It is hard to tell without a full log, parset and associated metadata like the regions and solutions files. Is it possible to extract the following for debugging purposes:
 - One scan (or a few minutes of data)
 - killms log
 - solutions dictionary (by default stored in your ms)
 - DDF parset and full log

so that we can look at reconstructing the tesselation schema that was used and trying to be applied?

**Comment by mauriliopannella** [comment] 2022-03-22 12:42
@IanHeywood here attached the reg files I used to input the peel and facet jobs.

\# Region file format: DS9 version 4.1
global color=green dashlist=8 3 width=1 font="helvetica 10 normal roman" select=1 highlite=1 dash=0 fixed=0 edit=1 move=1 delete=1 include=1 source=1
fk5
circle(11:40:48.1361,-26:29:08.500,10.000")

\# Region file format: DS9 version 4.1
global color=green dashlist=8 3 width=1 font="helvetica 10 normal roman" select=1 highlite=1 dash=0 fixed=0 edit=1 move=1 delete=1 include=1 source=1
fk5
circle(11:42:26.5145,-26:33:15.001,100.000")
circle(11:40:15.8364,-26:33:01.470,100.000")
circle(11:41:55.2864,-25:34:02.974,140.894")
circle(11:34:42.4075,-26:09:19.865,100.000")
circle(11:44:05.7459,-26:17:00.596,84.046")
circle(11:38:03.7727,-26:36:07.213,100.000")
circle(11:42:20.2081,-26:52:01.677,84.046")
circle(11:40:07.9913,-26:56:35.965,84.046")
circle(11:44:05.7459,-26:17:00.596,84.046")
circle(11:45:49.3001,-25:50:07.615,84.046")
circle(11:40:25.4445,-26:03:06.371,140.894")
circle(11:40:47.6445,-26:29:30.500,140.894")

**Comment by mauriliopannella** [comment] 2022-03-22 12:58
@bennahugo thanks for your feedback, I'll try to put together things asap. I'd probably need some help on that too but I'll see where I get first...

**Comment by mauriliopannella** [comment] 2022-03-22 14:33
Again me... after your suggestions that it could be possibly related to the actual reg file and the number/positions of the desired solutions. I have changed the number of entries in the facet.reg file and it is now actually running. It's definitely passed the previous stopping point... keep you posted. 
Thanks you! Maurilio

**Comment by bennahugo** [comment] 2022-03-22 14:41
Please do post the debugging set to us -- it would be useful to track this down for the next release.

**Comment by bennahugo** [comment] 2022-03-22 14:48
Nice spotting -- this could explain the identical distances from the facet centre :D which would induce failure I suspect in how that solution picking mechanism is implemented. One should probably do a sort and minimum selection (or argmin) on the distance instead for it to pick a unique distance.

**Comment by IanHeywood** [comment] 2022-03-22 14:51
I guess see if the issue triggers with a region file that has duplicate rows on the usual test data set? Might not be necessary for Maurilio to do extra work with uploading data etc.

**Comment by bennahugo** [comment] 2022-03-22 14:52
I will see if I can reproduce it this side on another dataset -- unfortunately edgecases are not necessarily easily reproducible

**Comment by mauriliopannella** [comment] 2022-03-22 15:36
> Please do post the debugging set to us -- it would be useful to track this down for the next release (even if you just fill the single scan dataset with zeros or something if you don't want to share any data).

I have no issue with sharing the data. It's just that today is a bad day and probably tomorrow will be too but I'll do it.

**Comment by IanHeywood** [comment] 2022-05-31 23:51
Closing this one for now. Please reopen if it turns out to be my problem.

**Closed by IanHeywood** 2022-05-31 23:51 UTC

**Comment by mauriliopannella** [comment] 2022-06-01 08:29
Hi Ian, yes indeed it was not your problem. In the end, I got stuck for quite a bit for a strange feedback that created between the software and the hardware setup. In a few words, to have killms working I had to  export OPENBLAS_NUM_THREADS=1
but this was then interfering with the DDF shared memory use on the node. In the end I have to use two different nodes for the DDF and killms runs... not sure it's the best possible solution but it's a working one for now.

If I may, and you still have the time and energy to read this, I´d like to ask your expert advice on the following matter. So, my observations are in the field of a very bright source (the Spiderweb radio galaxy, about 1Jy all together) plus there are at least a couple of 200 mJy sources nearby and not to far from the FWHP. What I have done so far, and that's the best image I managed to produce, is to peel the central radio galaxy and do a DDF on the bright sources nearby. Now, for the galaxy population in the field that's OKish and I can get close to the aimed sensitivity at the cost of weirdly removing away the main actor on the scene... Do you have suggestions on how this could better tackled? I am sure anything you'd have would be extremely helpful!

Thanks a lot,
Maurilio
