### ISSUE TITLE
project_info.p not generated

### ISSUE THREAD

**Issue by shilparanchod** [IanHeywood/oxkat#15] opened 2020-05-20 09:28 UTC
Hi Ian
I'm having an issue where the project_info.p file is not generated. I'm getting the following error:

WARNING: Couldn't write lextab module 'astropy.coordinates.angle_lextab'. [Errno 30] Read-only file system: '/usr/lib/python2.7/dist-packages/astropy/coordinates/angle_lextab.py'
WARNING: Couldn't create 'astropy.coordinates.angle_parsetab'. [Errno 30] Read-only file system: '/usr/lib/python2.7/dist-packages/astropy/coordinates/angle_parsetab.py'
Traceback (most recent call last):
  File "/scratch/users/shilpa/s1063again/oxkat/1GC_00_setup.py", line 213, in <module>
    main()
  File "/scratch/users/shilpa/s1063again/oxkat/1GC_00_setup.py", line 185, in main
    primary_field,primary_tag,secondary_field,target_list = get_field_info(myms)
  File "/scratch/users/shilpa/s1063again/oxkat/1GC_00_setup.py", line 120, in get_field_info
    return primary_field,primary_tag,secondary_fields,target_list
UnboundLocalError: local variable 'primary_field' referenced before assignment

**Comment by IanHeywood** [comment] 2020-05-20 09:55
Hi @shilparanchod. Can you please run the [ms_info.py](https://github.com/IanHeywood/oxkat/blob/master/tools/ms_info.py) script on your input MS and post the output in a code block?

Thanks.

**Comment by shilparanchod** [comment] 2020-05-20 11:08
--MS: 1530652463_sdp_l0.full_1284.full_pol.ms

     Observation start:        2018-07-03 21:16:53.060
     Observation end:          2018-07-04 06:40:06.764

     Track length:             33794.0 s (9.39 h)
     Mean integration time:    8.0 s

---- FIELDS:

     ROW   SOURCE_ID  NAME                  RA[hms]           DEC[dms]          RA[deg]   DEC[deg]  EXP[s]    EXP[h]
     0     0          1934-638              19h39m25.05s      -63d42m43.6s      294.8544  -63.7121  5280.0    1.467
     1     1          AbellS1063            22h48m43.5s       -44d31m44s        342.1812  -44.5289  23864.0   6.629
     2     2          J2314-4455            23h14m09.38s      -44d55m49.2s      348.5391  -44.9303  2032.0    0.564

---- SCANS:

     SCAN  SOURCE_ID  NAME                  LENGTH[s]         INTS        INTENT
     1     0          1934-638              592.0             74          CALIBRATE_BANDPASS,CALIBRATE_FLUX
     2     1          AbellS1063            584.0             73          TARGET
     3     2          J2314-4455            48.0              6           CALIBRATE_PHASE,CALIBRATE_AMPLI
     4     1          AbellS1063            584.0             73          TARGET
     5     2          J2314-4455            48.0              6           CALIBRATE_PHASE,CALIBRATE_AMPLI
     6     1          AbellS1063            584.0             73          TARGET
     7     2          J2314-4455            56.0              7           CALIBRATE_PHASE,CALIBRATE_AMPLI
     8     1          AbellS1063            592.0             74          TARGET
     9     2          J2314-4455            48.0              6           CALIBRATE_PHASE,CALIBRATE_AMPLI
     10    1          AbellS1063            584.0             73          TARGET
     11    0          1934-638              584.0             73          CALIBRATE_BANDPASS,CALIBRATE_FLUX
     12    2          J2314-4455            48.0              6           CALIBRATE_PHASE,CALIBRATE_AMPLI
     13    1          AbellS1063            584.0             73          TARGET
     14    2          J2314-4455            48.0              6           CALIBRATE_PHASE,CALIBRATE_AMPLI
     15    1          AbellS1063            584.0             73          TARGET
     16    2          J2314-4455            56.0              7           CALIBRATE_PHASE,CALIBRATE_AMPLI
     17    1          AbellS1063            592.0             74          TARGET
     18    2          J2314-4455            48.0              6           CALIBRATE_PHASE,CALIBRATE_AMPLI
     19    1          AbellS1063            584.0             73          TARGET
     20    2          J2314-4455            56.0              7           CALIBRATE_PHASE,CALIBRATE_AMPLI
     21    1          AbellS1063            584.0             73          TARGET
     22    0          1934-638              584.0             73          CALIBRATE_BANDPASS,CALIBRATE_FLUX
     23    2          J2314-4455            48.0              6           CALIBRATE_PHASE,CALIBRATE_AMPLI
     24    1          AbellS1063            584.0             73          TARGET
     25    2          J2314-4455            48.0              6           CALIBRATE_PHASE,CALIBRATE_AMPLI
     26    1          AbellS1063            584.0             73          TARGET
     27    2          J2314-4455            48.0              6           CALIBRATE_PHASE,CALIBRATE_AMPLI
     28    1          AbellS1063            584.0             73          TARGET
     29    2          J2314-4455            48.0              6           CALIBRATE_PHASE,CALIBRATE_AMPLI
     30    1          AbellS1063            592.0             74          TARGET
     31    2          J2314-4455            48.0              6           CALIBRATE_PHASE,CALIBRATE_AMPLI
     32    1          AbellS1063            584.0             73          TARGET
     33    0          1934-638              584.0             73          CALIBRATE_BANDPASS,CALIBRATE_FLUX
     34    2          J2314-4455            48.0              6           CALIBRATE_PHASE,CALIBRATE_AMPLI
     35    1          AbellS1063            584.0             73          TARGET
     36    2          J2314-4455            56.0              7           CALIBRATE_PHASE,CALIBRATE_AMPLI
     37    1          AbellS1063            592.0             74          TARGET
     38    2          J2314-4455            48.0              6           CALIBRATE_PHASE,CALIBRATE_AMPLI
     39    1          AbellS1063            584.0             73          TARGET
     40    2          J2314-4455            48.0              6           CALIBRATE_PHASE,CALIBRATE_AMPLI
     41    1          AbellS1063            584.0             73          TARGET
     42    2          J2314-4455            56.0              7           CALIBRATE_PHASE,CALIBRATE_AMPLI
     43    1          AbellS1063            584.0             73          TARGET
     44    0          1934-638              592.0             74          CALIBRATE_BANDPASS,CALIBRATE_FLUX
     45    2          J2314-4455            48.0              6           CALIBRATE_PHASE,CALIBRATE_AMPLI
     46    1          AbellS1063            584.0             73          TARGET
     47    2          J2314-4455            48.0              6           CALIBRATE_PHASE,CALIBRATE_AMPLI
     48    1          AbellS1063            592.0             74          TARGET
     49    2          J2314-4455            56.0              7           CALIBRATE_PHASE,CALIBRATE_AMPLI
     50    1          AbellS1063            584.0             73          TARGET
     51    2          J2314-4455            48.0              6           CALIBRATE_PHASE,CALIBRATE_AMPLI
     52    1          AbellS1063            584.0             73          TARGET
     53    2          J2314-4455            56.0              7           CALIBRATE_PHASE,CALIBRATE_AMPLI
     54    1          AbellS1063            584.0             73          TARGET
     55    0          1934-638              592.0             74          CALIBRATE_BANDPASS,CALIBRATE_FLUX
     56    2          J2314-4455            48.0              6           CALIBRATE_PHASE,CALIBRATE_AMPLI
     57    1          AbellS1063            584.0             73          TARGET
     58    2          J2314-4455            56.0              7           CALIBRATE_PHASE,CALIBRATE_AMPLI
     59    1          AbellS1063            592.0             74          TARGET
     60    2          J2314-4455            48.0              6           CALIBRATE_PHASE,CALIBRATE_AMPLI
     61    1          AbellS1063            584.0             73          TARGET
     62    2          J2314-4455            48.0              6           CALIBRATE_PHASE,CALIBRATE_AMPLI
     63    1          AbellS1063            584.0             73          TARGET
     64    2          J2314-4455            56.0              7           CALIBRATE_PHASE,CALIBRATE_AMPLI
     65    1          AbellS1063            592.0             74          TARGET
     66    0          1934-638              584.0             73          CALIBRATE_BANDPASS,CALIBRATE_FLUX
     67    2          J2314-4455            56.0              7           CALIBRATE_PHASE,CALIBRATE_AMPLI
     68    1          AbellS1063            592.0             74          TARGET
     69    2          J2314-4455            56.0              7           CALIBRATE_PHASE,CALIBRATE_AMPLI
     70    1          AbellS1063            592.0             74          TARGET
     71    2          J2314-4455            48.0              6           CALIBRATE_PHASE,CALIBRATE_AMPLI
     72    1          AbellS1063            584.0             73          TARGET
     73    2          J2314-4455            48.0              6           CALIBRATE_PHASE,CALIBRATE_AMPLI
     74    1          AbellS1063            584.0             73          TARGET
     75    2          J2314-4455            48.0              6           CALIBRATE_PHASE,CALIBRATE_AMPLI
     76    1          AbellS1063            584.0             73          TARGET
     77    0          1934-638              584.0             73          CALIBRATE_BANDPASS,CALIBRATE_FLUX
     78    2          J2314-4455            56.0              7           CALIBRATE_PHASE,CALIBRATE_AMPLI
     79    1          AbellS1063            592.0             74          TARGET
     80    2          J2314-4455            56.0              7           CALIBRATE_PHASE,CALIBRATE_AMPLI
     81    1          AbellS1063            592.0             74          TARGET
     82    2          J2314-4455            56.0              7           CALIBRATE_PHASE,CALIBRATE_AMPLI
     83    1          AbellS1063            592.0             74          TARGET
     84    2          J2314-4455            48.0              6           CALIBRATE_PHASE,CALIBRATE_AMPLI
     85    1          AbellS1063            584.0             73          TARGET
     86    2          J2314-4455            48.0              6           CALIBRATE_PHASE,CALIBRATE_AMPLI
     87    1          AbellS1063            584.0             73          TARGET
     88    0          1934-638              584.0             73          CALIBRATE_BANDPASS,CALIBRATE_FLUX
     89    2          J2314-4455            48.0              6           CALIBRATE_PHASE,CALIBRATE_AMPLI
     90    1          AbellS1063            408.0             51          TARGET

---- SPECTRAL WINDOWS:

     ROW   CHANS      WIDTH[MHz]            REF_FREQ[MHz]
     0     4096       0.208984375           1284.0

---- ANTENNAS:

     61 / 61 antennas in the main table

     ROW   NAME       POSITION
     0     m000       [ 5109224.29038545  2006790.35753831 -3239100.60907827]
     1     m001       [ 5109237.63048662  2006805.67916798 -3239069.98867308]
     2     m002       [ 5109224.98620835  2006765.00652684 -3239115.20043854]
     3     m003       [ 5109247.7157809   2006736.96831224 -3239096.13639116]
     4     m004       [ 5109244.68621342  2006674.42740404 -3239139.81502283]
     5     m005       [ 5109222.76106102  2006688.94849795 -3239165.94167899]
     6     m006       [ 5109186.50072392  2006764.80518593 -3239176.6832991 ]
     7     m007       [ 5109162.04576619  2006678.53525529 -3239269.23392149]
     8     m008       [ 5109101.13948279  2006650.38001812 -3239383.31891167]
     9     m009       [ 5109132.81491624  2006798.06346825 -3239242.1849703 ]
     10    m010       [ 5109046.33257705  2006823.98423929 -3239363.78875328]
     11    m011       [ 5109122.9653619   2006849.69737412 -3239225.88323836]
     12    m012       [ 5109095.03238529  2006898.89823927 -3239239.95261248]
     13    m013       [ 5109048.21140523  2006984.47921695 -3239261.95508702]
     14    m014       [ 5109082.8918671   2007045.24176653 -3239169.09131402]
     15    m015       [ 5109139.53289849  2006992.25575245 -3239111.37956843]
     16    m016       [ 5109127.08092444  2007070.64752542 -3239082.81663487]
     17    m017       [ 5109193.73985697  2007001.70702165 -3239019.08886714]
     18    m018       [ 5109165.01295758  2006889.5433449  -3239134.24908956]
     19    m019       [ 5109122.95504772  2006942.9230536  -3239168.3618385 ]
     20    m021       [ 5109272.05901937  2006500.01941379 -3239203.48570092]
     21    m022       [ 5109454.06785286  2006488.74182014 -3238920.41309529]
     22    m023       [ 5109368.62360157  2006509.64851116 -3239043.72292735]
     23    m024       [ 5109516.48176627  2006536.84887533 -3238791.43182064]
     24    m025       [ 5109490.75061883  2006708.38364351 -3238726.60664016]
     25    m026       [ 5109362.66269762  2006747.22097025 -3238906.81814232]
     26    m027       [ 5109293.30009769  2006869.8275163  -3238941.8013792 ]
     27    m028       [ 5109296.30037041  2006772.53436918 -3238996.83759835]
     28    m029       [ 5109292.53864301  2006730.67870515 -3239028.63504313]
     29    m030       [ 5109310.2977957   2007017.0371345  -3238823.74833534]
     30    m031       [ 5109273.32322089  2007083.40054198 -3238841.20407917]
     31    m032       [ 5109233.60247272  2007298.47483172 -3238770.86653967]
     32    m033       [ 5109514.1862076   2007536.98018719 -3238177.03761655]
     33    m034       [ 5109175.83425585  2007164.6225741  -3238946.9157957 ]
     34    m036       [ 5109041.41107829  2007144.53959897 -3239173.49987046]
     35    m037       [ 5108965.29396408  2007106.07798817 -3239319.10626408]
     36    m038       [ 5108973.9741227   2006930.08815389 -3239413.36535278]
     37    m039       [ 5108948.61877179  2006963.57240683 -3239433.44556484]
     38    m040       [ 5108993.64502175  2006679.78785901 -3239536.3704696 ]
     39    m041       [ 5109111.46526165  2006445.98820889 -3239491.95574845]
     40    m043       [ 5109486.39986795  2006225.48918911 -3239031.01140517]
     41    m044       [ 5109925.48993011  2006111.83927162 -3238401.39137192]
     42    m045       [ 5110109.89167353  2005177.90721032 -3238688.71487862]
     43    m046       [ 5110676.49309192  2005793.15912039 -3237408.15958056]
     44    m047       [ 5109284.52911273  2006201.59095546 -3239366.63085706]
     45    m048       [ 5111608.06713389  2004721.2262196  -3236602.97648213]
     46    m049       [ 5110840.88031587  2003560.05835788 -3238544.12229424]
     47    m050       [ 5109666.45350777  2004767.93425934 -3239646.10724868]
     48    m051       [ 5109264.13184507  2005901.39357078 -3239583.34023681]
     49    m052       [ 5108992.20384711  2006070.76823301 -3239910.94039101]
     50    m053       [ 5108701.4416573   2006603.93170569 -3240047.18931249]
     51    m054       [ 5108767.23563213  2007556.54497446 -3239354.53798391]
     52    m055       [ 5108927.44284297  2007973.80069955 -3238840.15661171]
     53    m056       [ 5108955.98627893  2008411.12952127 -3238520.35100512]
     54    m057       [ 5110746.29394702  2007713.62376395 -3236109.83563026]
     55    m058       [ 5109561.42891041  2009946.10154943 -3236606.07622565]
     56    m059       [ 5108335.37384839  2010410.68719286 -3238271.56790951]
     57    m060       [ 5107206.7556267   2009680.79691055 -3240512.45932645]
     58    m061       [ 5108231.34344288  2006391.59690538 -3240926.75417832]
     59    m062       [ 5108666.77102205  2005032.4814725  -3241081.69797118]
     60    m063       [ 5109701.33552042  2003312.70128824 -3240508.72093974]

**Comment by IanHeywood** [comment] 2020-05-20 11:31
I think the problem here is the position of the primary. I use a positional match to determine whether either 1934 or 0408 is used as the primary, but the separation criterion is a bit strict, and the primary positions are sometimes a bit off in older MeerKAT observations.

I already checked in a fix for this here 59fbab2022e8d47d041ab31e240a35a0caa8dacb but it hasn't made it to the master branch yet. 

If you relax the separation criterion here:

https://github.com/IanHeywood/oxkat/blob/master/oxkat/1GC_00_setup.py#L96

Hopefully it will fix the issue...

Cheers.

**Comment by shilparanchod** [comment] 2020-05-21 10:23
Thanks!

**Comment by IanHeywood** [comment] 2020-05-21 10:55
You're welcome!

I'll assume the issue is resolved but please reopen if not.

Cheers.

**Comment by rdeane** [comment] 2020-05-21 20:06
Hey @IanHeywood, I hit the same issue today. I increased the `sep` tolerance to 5e-3, but same error. Looking back, SARAO emailed about these position errors for B1934 & J0408 for data observed before November 2019, but the differences are well within the increased tolerance of 5e-3 degrees (0.52'' and 2.0'' respectively). 

The MS in question is a split version of Tariq's cluster, kept at 209 kHz resolution. Details: 

```--MS: 1557579065_sdp_l0_chan2200-2600_wtspec.ms

     Observation start:        2019-05-11 12:51:36.267
     Observation end:          2019-05-11 20:51:32.084

     Track length:             28796.0 s (8.0 h)
     Mean integration time:    8.0 s

---- FIELDS:

     ROW   SOURCE_ID  NAME                  RA[hms]           DEC[dms]          RA[deg]   DEC[deg]  EXP[s]    EXP[h]
     0     0          J0408-6545            04h08m20.38s      -65d45m09.6s      62.0849   -65.7527  1752.0    0.487
     1     1          J0825-5010            08h25m26.86s      -50d10m38.5s      126.3619  -50.1774  3104.0    0.862
     2     2          Abell3408             07h08m31.7s       -49d12m52s        107.1321  -49.2144  21288.0   5.913
     3     3          3C286                 13h31m08.29s      +30d30m33s        202.7845  30.5092   584.0     0.162
```



I'll dig a little deeper tomorrow, but let me know if there is anything obvious. 

Thanks

**Comment by IanHeywood** [comment] 2020-05-21 21:11
Dang! Are the scan intents intact? Are they visible in the full ms_info output?

**Comment by rdeane** [comment] 2020-05-22 07:34
Sorry, should have included them: 

```
---- SCANS:

     SCAN  SOURCE_ID  NAME                  LENGTH[s]         INTS        INTENT
     1     0          J0408-6545            584.0             73          CALIBRATE_BANDPASS,CALIBRATE_FLUX
     2     1          J0825-5010            104.0             13          CALIBRATE_PHASE,CALIBRATE_AMPLI
     3     2          Abell3408             888.0             111         None
     4     1          J0825-5010            104.0             13          CALIBRATE_PHASE,CALIBRATE_AMPLI
     5     2          Abell3408             880.0             110         None
     6     1          J0825-5010            104.0             13          CALIBRATE_PHASE,CALIBRATE_AMPLI
     7     2          Abell3408             888.0             111         None
     8     1          J0825-5010            104.0             13          CALIBRATE_PHASE,CALIBRATE_AMPLI
     9     2          Abell3408             888.0             111         None
     10    1          J0825-5010            104.0             13          CALIBRATE_PHASE,CALIBRATE_AMPLI
     11    2          Abell3408             888.0             111         None
     12    1          J0825-5010            104.0             13          CALIBRATE_PHASE,CALIBRATE_AMPLI
     13    2          Abell3408             888.0             111         None
     14    1          J0825-5010            112.0             14          CALIBRATE_PHASE,CALIBRATE_AMPLI
     15    2          Abell3408             880.0             110         None
     16    0          J0408-6545            584.0             73          CALIBRATE_BANDPASS,CALIBRATE_FLUX
     17    1          J0825-5010            104.0             13          CALIBRATE_PHASE,CALIBRATE_AMPLI
     18    2          Abell3408             888.0             111         None
```

**Comment by IanHeywood** [comment] 2020-05-22 09:16
Hi @rdeane, thanks for that. The target has a "None" intent which will trip up the assumptions the setup script makes.

You can probably fudge it by modifying this line accordingly:

https://github.com/IanHeywood/oxkat/blob/master/oxkat/1GC_00_setup.py#L37

I'm guessing it's a string the MS column rather than the python null value. This is the sort of thing I'm slowly moving into the config file for convenience, but this might be the best solution for the moment.

Cheers.

**Comment by rdeane** [comment] 2020-05-23 06:14
aha, the calibrator separations were a red herring and I wasn't looking at the obvious. I've edited the scan intents, but there seem to be some knock-on effects. The ```project_info.p``` file is created now, so let's leave this issue closed and I will post the other issues if I can't resolve them.

**Comment by IanHeywood** [comment] 2020-05-23 11:47
Please post them anyway if you have time! Would like to know why it's failing.

Cheers.

**Closed by IanHeywood** 2020-05-23 11:47 UTC
